# Generated by Django 5.1.2 on 2024-10-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dothraki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fahim',
            new_name='Member',
        ),
    ]
