# Generated by Django 5.1.2 on 2024-10-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dothraki', '0002_rename_fahim_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Fahim',
        ),
    ]
