# Generated by Django 5.1.2 on 2024-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothraki', '0004_mumina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_added', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ashley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_added', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nickson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_added', models.DateField(null=True)),
            ],
        ),
    ]
