# Generated by Django 5.1.2 on 2024-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothraki', '0005_ahlam_ashley_nickson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_added', models.DateField(null=True)),
            ],
        ),
    ]
